import = [
    "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

[shell]
program = "/bin/fish"

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Block"
unfocused_hollow = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" } # Default for Linux/BSD: "monospace", Regular
bold = { style = "Bold" } # Inherits family from normal, Default style: Bold
italic = { style = "Italic" } # Inherits family from normal, Default style: Italic
bold_italic = { style = "Bold Italic" } # Inherits family from normal, Default style: Bold Italic

# Font size in points
size = 16.0

# Offset is extra space around each character
offset = { x = 0, y = 0 } # Default: x = 0, y = 0

# Glyph offset determines the locations of the glyphs within their cells
glyph_offset = { x = 0, y = 0 } # Default: x = 0, y = 0

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[scrolling]
history = 10000
multiplier = 3

[window]
# decorations = "none"
opacity = 0.95
dimensions = { columns = 140, lines = 38 }
padding = { x = 10, y = 10 }  # Default: x = 0, y = 0
